
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 02 17:02:46 GMT-03:00 2008
//----------------------------------------------------

package microc.syntax;

/** CUP generated class containing symbol constants. */
public class SymbolType {
  /* terminals */
  public static final int TIPO_CHAR = 30;
  public static final int MENOS = 5;
  public static final int OU = 6;
  public static final int MENOR = 9;
  public static final int ELSE = 24;
  public static final int IGUAL = 13;
  public static final int MAIOR_IGUAL = 12;
  public static final int WHILE = 25;
  public static final int DIVIDIDO = 3;
  public static final int MENOR_IGUAL = 10;
  public static final int RETURN = 27;
  public static final int IF = 23;
  public static final int DO = 26;
  public static final int MAIS = 4;
  public static final int E = 7;
  public static final int EOF = 0;
  public static final int VIRG = 17;
  public static final int DIFERENTE = 14;
  public static final int MAIN = 22;
  public static final int RECEBE = 15;
  public static final int PT_VIRG = 16;
  public static final int error = 1;
  public static final int MAIOR = 11;
  public static final int IDENTIFICADOR = 31;
  public static final int ABRE_CHAVE = 20;
  public static final int LITERAL_INT = 34;
  public static final int LITERAL_CHAR = 32;
  public static final int MENOS_UNARIO = 8;
  public static final int VEZES = 2;
  public static final int FECHA_PAR = 19;
  public static final int LITERAL_FLOAT = 33;
  public static final int FECHA_CHAVE = 21;
  public static final int TIPO_INT = 28;
  public static final int TIPO_FLOAT = 29;
  public static final int ABRE_PAR = 18;
}

