
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 17 00:56:28 GMT-03:00 2009
//----------------------------------------------------

package tlanguage.version0;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LEFT_BRACE = 14;
  public static final int GOTO = 7;
  public static final int ACCEPT = 10;
  public static final int IDENTIFIER = 13;
  public static final int IF = 3;
  public static final int IF_NOT = 4;
  public static final int COLON = 19;
  public static final int WRITE = 5;
  public static final int RIGHT = 9;
  public static final int SYMBOL_LITERAL = 12;
  public static final int LEFT = 8;
  public static final int EOF = 0;
  public static final int REJECT = 11;
  public static final int LEFT_BRACKET = 16;
  public static final int error = 1;
  public static final int INPUT_SET = 2;
  public static final int DOT_DOT = 18;
  public static final int RIGHT_BRACE = 15;
  public static final int LINE_BREAK = 20;
  public static final int MOVE = 6;
  public static final int RIGHT_BRACKET = 17;
}

