
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 24 16:03:44 GMT-03:00 2014
//----------------------------------------------------

package xpr.version1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIS = 2;
  public static final int DIVIDE = 5;
  public static final int MENOS = 3;
  public static final int MENOS_UNARIO = 6;
  public static final int EOF = 0;
  public static final int VEZES = 4;
  public static final int NUMERO = 13;
  public static final int ATRIBUI = 10;
  public static final int error = 1;
  public static final int DEF = 11;
  public static final int ABRE_PAR = 8;
  public static final int PT_VIRG = 7;
  public static final int IDENTIFICADOR = 12;
  public static final int FECHA_PAR = 9;
}

