/* The following code was generated by JFlex 1.4.1 on 28/05/09 01:09 */

package tlanguage.version1;

import tlanguage.Token;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 28/05/09 01:09 from the specification file
 * <tt>D:/Projetos/Projetos de Compiladores/T-language/src/tlanguage/Lexer.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 43,  0,  1,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  0,  0,  0,  0,  0,  0,  0,  4,  5,  0,  0,  7, 17,  6, 46, 
    45, 45, 45, 45, 45, 45, 45, 45, 45, 45,  8,  9,  0,  0,  0,  0, 
     0, 34, 44, 35, 44, 36, 44, 44, 44, 44, 41, 44, 44, 44, 44, 44, 
    37, 44, 40, 44, 38, 44, 44, 44, 44, 44, 44,  0,  0,  0,  0, 45, 
     0, 28, 25, 20, 22, 19, 29, 32, 33, 12, 39, 42, 26, 24, 13, 21, 
    14, 44, 27, 18, 16, 15, 31, 30, 44, 23, 44,  2, 10,  3, 11,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\7\1\10\1\11\1\12\1\13\20\1\1\14\2\15"+
    "\1\16\17\15\1\17\22\15\1\20\2\15\1\21\1\22"+
    "\1\15\1\23\4\15\1\24\6\15\1\25\2\15\1\26"+
    "\3\15\1\27\2\15\1\30\1\31\6\15\1\32\1\33"+
    "\1\34";

  private static int [] zzUnpackAction() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\57\0\57\0\57\0\57\0\215"+
    "\0\57\0\57\0\57\0\57\0\57\0\274\0\353\0\u011a"+
    "\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u031f\0\u034e\0\u037d\0\57\0\353\0\u03ac"+
    "\0\353\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5"+
    "\0\u0524\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d"+
    "\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5"+
    "\0\u0814\0\u0843\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d"+
    "\0\u098c\0\u09bb\0\u09ea\0\353\0\u0a19\0\u0a48\0\353\0\353"+
    "\0\u0a77\0\353\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\353\0\u0b62"+
    "\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\353\0\u0c7c\0\u0cab"+
    "\0\353\0\u0cda\0\u0d09\0\u0d38\0\353\0\u0d67\0\u0d96\0\353"+
    "\0\353\0\u0dc5\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0\0\353"+
    "\0\353\0\353";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\4\17\1\2\1\20"+
    "\1\21\1\22\1\17\1\23\1\17\1\24\1\25\1\26"+
    "\1\27\1\30\1\17\1\31\1\17\1\32\1\17\1\33"+
    "\5\17\1\34\2\17\1\3\1\17\1\2\1\35\60\0"+
    "\1\3\51\0\1\3\11\0\1\36\64\0\1\37\1\40"+
    "\17\37\1\41\15\37\1\0\2\37\15\0\37\37\1\0"+
    "\2\37\15\0\13\37\1\42\23\37\1\0\2\37\15\0"+
    "\16\37\1\43\20\37\1\0\2\37\15\0\11\37\1\44"+
    "\25\37\1\0\2\37\15\0\1\45\36\37\1\0\2\37"+
    "\15\0\11\37\1\46\6\37\1\47\16\37\1\0\2\37"+
    "\15\0\16\37\1\50\20\37\1\0\2\37\15\0\7\37"+
    "\1\51\27\37\1\0\2\37\15\0\1\52\6\37\1\53"+
    "\27\37\1\0\2\37\15\0\10\37\1\54\26\37\1\0"+
    "\2\37\15\0\17\37\1\55\17\37\1\0\2\37\15\0"+
    "\11\37\1\56\25\37\1\0\2\37\15\0\27\37\1\57"+
    "\7\37\1\0\2\37\15\0\30\37\1\60\6\37\1\0"+
    "\2\37\57\0\1\61\14\0\2\37\1\62\34\37\1\0"+
    "\2\37\15\0\14\37\1\63\22\37\1\0\2\37\15\0"+
    "\6\37\1\64\30\37\1\0\2\37\15\0\1\37\1\65"+
    "\35\37\1\0\2\37\15\0\17\37\1\66\17\37\1\0"+
    "\2\37\15\0\23\37\1\67\13\37\1\0\2\37\15\0"+
    "\1\70\36\37\1\0\2\37\15\0\20\37\1\71\16\37"+
    "\1\0\2\37\15\0\21\37\1\72\15\37\1\0\2\37"+
    "\15\0\24\37\1\73\12\37\1\0\2\37\15\0\33\37"+
    "\1\74\3\37\1\0\2\37\15\0\10\37\1\75\26\37"+
    "\1\0\2\37\15\0\1\76\36\37\1\0\2\37\15\0"+
    "\4\37\1\77\32\37\1\0\2\37\15\0\27\37\1\100"+
    "\7\37\1\0\2\37\15\0\35\37\1\101\1\37\1\0"+
    "\2\37\1\0\53\61\1\0\3\61\14\0\3\37\1\102"+
    "\33\37\1\0\2\37\15\0\15\37\1\103\21\37\1\0"+
    "\2\37\15\0\7\37\1\104\27\37\1\0\2\37\15\0"+
    "\12\37\1\105\24\37\1\0\2\37\15\0\7\37\1\106"+
    "\27\37\1\0\2\37\15\0\7\37\1\107\27\37\1\0"+
    "\2\37\15\0\1\37\1\110\35\37\1\0\2\37\15\0"+
    "\1\37\1\111\35\37\1\0\2\37\15\0\4\37\1\112"+
    "\32\37\1\0\2\37\15\0\25\37\1\113\11\37\1\0"+
    "\2\37\15\0\7\37\1\114\27\37\1\0\2\37\15\0"+
    "\7\37\1\115\27\37\1\0\2\37\15\0\4\37\1\116"+
    "\32\37\1\0\2\37\15\0\11\37\1\117\25\37\1\0"+
    "\2\37\15\0\30\37\1\120\6\37\1\0\2\37\15\0"+
    "\30\37\1\121\6\37\1\0\2\37\15\0\4\37\1\122"+
    "\32\37\1\0\2\37\15\0\11\37\1\123\25\37\1\0"+
    "\2\37\15\0\1\124\36\37\1\0\2\37\15\0\10\37"+
    "\1\125\26\37\1\0\2\37\15\0\36\37\1\17\1\0"+
    "\2\37\15\0\4\37\1\126\32\37\1\0\2\37\15\0"+
    "\10\37\1\127\26\37\1\0\2\37\15\0\2\37\1\130"+
    "\34\37\1\0\2\37\15\0\7\37\1\131\27\37\1\0"+
    "\2\37\15\0\31\37\1\132\5\37\1\0\2\37\15\0"+
    "\27\37\1\133\7\37\1\0\2\37\15\0\5\37\1\134"+
    "\31\37\1\0\2\37\15\0\16\37\1\135\20\37\1\0"+
    "\2\37\15\0\4\37\1\136\32\37\1\0\2\37\15\0"+
    "\4\37\1\137\32\37\1\0\2\37\15\0\4\37\1\140"+
    "\32\37\1\0\2\37\15\0\4\37\1\141\32\37\1\0"+
    "\2\37\15\0\32\37\1\141\4\37\1\0\2\37\15\0"+
    "\32\37\1\140\4\37\1\0\2\37\15\0\6\37\1\142"+
    "\30\37\1\0\2\37\15\0\1\143\36\37\1\0\2\37"+
    "\15\0\1\144\36\37\1\0\2\37\15\0\7\37\1\145"+
    "\27\37\1\0\2\37\15\0\11\37\1\146\25\37\1\0"+
    "\2\37\15\0\11\37\1\147\25\37\1\0\2\37\15\0"+
    "\4\37\1\150\32\37\1\0\2\37\15\0\1\37\1\151"+
    "\35\37\1\0\2\37\15\0\1\37\1\152\35\37\1\0"+
    "\2\37\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3807];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\4\11\1\1\5\11\20\1\1\11"+
    "\114\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[106];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	//Para facilitar a criação dos tokens.
	Token newToken(int tokenId) {
    	return new Token(tokenId, yyline+1, yycolumn+1, yytext());
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return newToken(sym.SYMBOL_LITERAL);
          }
        case 29: break;
        case 15: 
          { // Comentários de linha.
          }
        case 30: break;
        case 17: 
          { return newToken(sym.MOVE);
          }
        case 31: break;
        case 11: 
          { return newToken(sym.NOT);
          }
        case 32: break;
        case 24: 
          { return newToken(sym.REJECT);
          }
        case 33: break;
        case 12: 
          { return newToken(sym.DOT_DOT);
          }
        case 34: break;
        case 22: 
          { return newToken(sym.WRITE);
          }
        case 35: break;
        case 25: 
          { return newToken(sym.ACCEPT);
          }
        case 36: break;
        case 4: 
          { return newToken(sym.RIGHT_BRACE);
          }
        case 37: break;
        case 14: 
          { return newToken(sym.IF);
          }
        case 38: break;
        case 6: 
          { return newToken(sym.RIGHT_PAR);
          }
        case 39: break;
        case 18: 
          { return newToken(sym.MAIN);
          }
        case 40: break;
        case 20: 
          { return newToken(sym.GOTO);
          }
        case 41: break;
        case 27: 
          { return newToken(sym.CONDITION_TYPE);
          }
        case 42: break;
        case 23: 
          { return newToken(sym.SYMBOL_TYPE);
          }
        case 43: break;
        case 2: 
          { // Espaços em branco.
          }
        case 44: break;
        case 21: 
          { return newToken(sym.RIGHT);
          }
        case 45: break;
        case 19: 
          { return newToken(sym.LEFT);
          }
        case 46: break;
        case 28: 
          { return newToken(sym.DIRECTION_TYPE);
          }
        case 47: break;
        case 26: 
          { return newToken(sym.INPUT_SET);
          }
        case 48: break;
        case 5: 
          { return newToken(sym.LEFT_PAR);
          }
        case 49: break;
        case 8: 
          { return newToken(sym.COLON);
          }
        case 50: break;
        case 16: 
          { return newToken(sym.ELSE);
          }
        case 51: break;
        case 9: 
          { return newToken(sym.SEMICOLON);
          }
        case 52: break;
        case 7: 
          { return newToken(sym.COMMA);
          }
        case 53: break;
        case 13: 
          { return newToken(sym.IDENTIFIER);
          }
        case 54: break;
        case 3: 
          { return newToken(sym.LEFT_BRACE);
          }
        case 55: break;
        case 10: 
          { return newToken(sym.OR);
          }
        case 56: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {
                return newToken(sym.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
