
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 28 01:07:16 GMT-03:00 2009
//----------------------------------------------------

package tlanguage.version1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 27;
  public static final int DIRECTION_TYPE = 5;
  public static final int ELSE = 8;
  public static final int LEFT_BRACE = 20;
  public static final int OR = 16;
  public static final int GOTO = 11;
  public static final int ACCEPT = 14;
  public static final int NOT = 17;
  public static final int IDENTIFIER = 19;
  public static final int CONDITION_TYPE = 3;
  public static final int SYMBOL_TYPE = 4;
  public static final int IF = 7;
  public static final int COLON = 26;
  public static final int WRITE = 9;
  public static final int RIGHT = 13;
  public static final int LEFT_PAR = 22;
  public static final int COMMA = 25;
  public static final int SYMBOL_LITERAL = 18;
  public static final int LEFT = 12;
  public static final int EOF = 0;
  public static final int RIGHT_PAR = 23;
  public static final int MAIN = 6;
  public static final int REJECT = 15;
  public static final int error = 1;
  public static final int INPUT_SET = 2;
  public static final int DOT_DOT = 24;
  public static final int RIGHT_BRACE = 21;
  public static final int MOVE = 10;
}

