
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 07 10:59:31 BRT 2022
//----------------------------------------------------

package xpr.version1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAIS = 2;
  public static final int DIVIDE = 5;
  public static final int MENOS = 3;
  public static final int EOF = 0;
  public static final int VEZES = 4;
  public static final int NUMERO = 12;
  public static final int ATRIBUI = 9;
  public static final int error = 1;
  public static final int DEF = 10;
  public static final int ABRE_PAR = 7;
  public static final int PT_VIRG = 6;
  public static final int IDENTIFICADOR = 11;
  public static final int FECHA_PAR = 8;
}

